---
title: "data_manipulation"
author: "Mia Yu"
date: "2023-09-19"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
```

Inport FAS litters and pups.

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df) # make the name of variables in litters_df cleaner

pups_df = 
  read_csv("data/FAS_pups.csv")
puprs_df = janitor::clean_names(pups_df)
```

## `select`

`select` is used to select columns!

```{r}
select(litters_df, group, litter_number, gd0_weight) # only show litternumber and gd0weight

select(litters_df, group, gd0_weight:gd_of_birth) #show the vec from gd0weight to gdofbirth

select(litters_df, group, starts_with("pups")) #show the vec started with "pups"

select(litters_df, -litter_number) #remove vec litter_number

select(litters_df, -starts_with("gd")) #remove vec started with gd

select(litters_df, group, litter_id = litter_number) #rename litter_id

select(litters_df, group, litter_id = litter_number, everything()) #rename litter_id but keep everything afterward

select(litters_df, gd0_weight, everything()) #reorder (show the gd0_weight first and keep everything else)

#not saving everything

# litters_df = select(litters_df, group, litter_number, gd0_weight) # rewrite (save)
```

do the same thing as:

```{r}
rename(litters_df, litter_id = litter_number)

relocate(litters_df, litter_number)
```

`select` vs `pull
```{r}
select(litters_df, group)
pull(litters_df, group) # replace the "$", doesn't exsit dataframe, float
```

## `filter`

get rid of rows using `filter()`

```{r}
filter(litters_df, group == "Con7" ) # only leave the group is Con7

filter(litters_df, group != "Con7" )
filter(litters_df, !(group == "Con7"))

# "<, >, !="

filter(litters_df, group == "Con7" | group == "Mod8")
filter(litters_df, group %in% c("Con7", "Mod8"))
```

what about missing rows

```{r}
drop_na(litters_df) # get rid of all the colums having missing value
drop_na(litters_df, gd0_weight)
```

## `mutate

this is used to add or change variables

```{r}
mutate(litters_df, wt_gain = gd18_weight - gd0_weight) # create a new vec

mutate(litters_df, group = str_to_lower(group)) # equal to the lower case

mutate(litters_df,
       wt_gain = gd18_weight - gd0_weight,
       group = str_to_lower(group))
```

## `arrange`

```{r}
arrange(litters_df, gd0_weight)

arrange(litters_df, group, gd0_weight) # order the colums by first group and after gd0weight

```